### ISSUE TITLE
Same savegames parsed multiple times summing up wrong objectives totals

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#100]
Same savegames are counted as different ones again and again, making wrong calcullation of the objective (kills, secrets, items) totals.

https://imgur.com/a/Y8npGUE

**Comment by hobomaster22** [comment]
Should be resolved with this build:
https://ci.appveyor.com/api/buildjobs/a90s6kar95p1kyl2/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
I deleted the offending statistics and played some more maps and seems to behave right again. I'll reopen the issue if I see it happening again, thank you very much!
