### ISSUE TITLE
Crash when ordering "untagged" view by "download" date descending order

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#103]
Only on "untagged" tab, only when ordering by "download" date (and order descending, most recent top) by clicking the header,  DoomLauncher crashes with the dump attached below.

Ordering "untagged" tab by any other column like "name" or "last played" date, or by "download" but in ascending order (first order it chooses when cliecked), or ordering any other tab by any column, included "download" descending, doesn't crash DoomLauncher.

I then must recover from SQLite backup as DoomLauncher crashes everytime I try to launch it again.

** Error dump (sorry, in spanish): **

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.InvalidOperationException: El objeto que acepta valores Null debe tener un valor.
   en System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   en DoomLauncher.StatsControl.SetStatistics(IEnumerable`1 gameFiles, IEnumerable`1 stats)
   en DoomLauncher.StatsControl.SetStatistics(IGameFile gameFile, IEnumerable`1 stats)
   en DoomLauncher.GameFileSummary.SetStatistics(IGameFile gameFile, IEnumerable`1 stats)
   en DoomLauncher.MainForm.HandleSelectionChange(Object sender, Boolean forceChange)
   en DoomLauncher.MainForm.ctrlView_SelectionChange(Object sender, EventArgs e)
   en DoomLauncher.GameFileViewControl.HandleSelection()
   en DoomLauncher.GameFileViewControl.dgvMain_CellClick(Object sender, DataGridViewCellEventArgs e)
   en System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   en System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.DataGridView.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3394.0 built by: NET472REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DoomLauncher
    Versión del ensamblado: 2.6.4.1
    Versión Win32: 2.6.4.1
    Código base: file:///P:/Ports/Doom/DoomLauncher/DoomLauncher.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3324.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3362.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3362.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CheckBoxComboBox
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base: file:///P:/Ports/Doom/DoomLauncher/CheckBoxComboBox.DLL
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Data
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3260.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Data.SQLite
    Versión del ensamblado: 1.0.92.0
    Versión Win32: 1.0.92.0
    Código base: file:///P:/Ports/Doom/DoomLauncher/System.Data.SQLite.DLL
----------------------------------------
System.Transactions
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3221.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Data.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Data.resources.dll
----------------------------------------
System.Numerics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.CSharp
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versión del ensamblado: 0.0.0.0
    Versión Win32: 4.7.3394.0 built by: NET472REL1LAST_C
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Dynamic.DynamicAssembly
    Versión del ensamblado: 0.0.0.0
    Versión Win32: 4.7.3056.0
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.GeneratedCode
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Equin.ApplicationFramework.BindingListView
    Versión del ensamblado: 1.2.2446.31718
    Versión Win32: 1.2.0.0
    Código base: file:///P:/Ports/Doom/DoomLauncher/Equin.ApplicationFramework.BindingListView.DLL
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.7.3056.0 built by: NET472REL1
    Código base: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by hobomaster22** [comment]
Can you attach or give me a link to your sqlite database that's causing the crash?

**Comment by mgtroyas** [comment]
[DoomLauncher.zip](https://github.com/hobomaster22/DoomLauncher/files/3145255/DoomLauncher.zip)

**Comment by hobomaster22** [comment]
Thanks! Should be fixed here:
https://ci.appveyor.com/api/buildjobs/gsrj75su2f8aamoe/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

For future reference, these are development builds and may have issues. If you run into another problem that stops you from playing you can always go back to the official master release until the problem is resolved.

**Comment by mgtroyas** [comment]
Thank you, is solved now.

I have no problem using the dev builds and having issues if I'm helping to find bugs and enhancements, if I totally break my installation I'll revert back to the stable one, don't worry.
