### ISSUE TITLE
Only show relevant tags when adding/deleting

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#114]
Instead of showing all the existing tags on both add and delete tags submenus, only not assigned tags should be shown to choose add, and only assigned should be shown to choose untag.

**Comment by hobomaster22** [comment]
Available on this build:

https://ci.appveyor.com/api/buildjobs/q402hy0u0iyhubfc/artifacts/ReleaseBuild%2FDoomLauncher_2.6.5.0.zip
