### ISSUE TITLE
Unhandled exception error

### ISSUE THREAD

**Issue by lvangh** [hobomaster22/DoomLauncher#118]
Hello, tried launcher for the first time and added a couple files, then hit the open button and got an error. 

![image](https://user-images.githubusercontent.com/19690096/63644771-4e798100-c6a5-11e9-8f01-b176a5dccc59.png)

pastebin:
https://pastebin.com/G9SzCk03

**Comment by hobomaster22** [comment]
Thanks for the report, it should be fixed here:

https://ci.appveyor.com/api/buildjobs/j5a3rwlo99h80eea/artifacts/ReleaseBuild%2FDoomLauncher_2.6.5.0.zip
