### ISSUE TITLE
21:9 aspect ratio screenshots compressed on thumbnails

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#121]
I've recently switched to a 21:9 monitor (2560x1080 resolution). I've noticed screenshot thumbnails are shown on another more traditional aspect ratio, compressed horizontally.

**Comment by hobomaster22** [comment]
Fixed on development. The picture box views should handle different aspect ratios now.

https://ci.appveyor.com/api/buildjobs/kxfcnysth2uund3p/artifacts/ReleaseBuild%2FDoomLauncher_2.6.5.0.zip
