### ISSUE TITLE
Files that are automatically loaded for a source port don't leave the Additional Files menu (with IWads?)

### ISSUE THREAD

**Issue by robbinsrush** [hobomaster22/DoomLauncher#19]
Long title but it gets the gist of it.

Say I have a Zandronum load 3 files when starting, and then want to play just Doom2 with that source port and those files. I load Doom2 from the IWads, play, and later exit. If I want to play Doom2 with another source port, the last one's files don't get removed from the Additional Files prompt unless I do it manually.

I have attached some examples.
![doomlauncher_2018-08-31_15-19-27](https://user-images.githubusercontent.com/25468624/44938173-18275100-ad32-11e8-8f80-387ac9bfe9e3.png)

![doomlauncher_2018-08-31_15-19-34](https://user-images.githubusercontent.com/25468624/44938177-1cec0500-ad32-11e8-8ccb-4c08055d6e3c.png)

![doomlauncher_2018-08-31_15-20-23](https://user-images.githubusercontent.com/25468624/44938179-1fe6f580-ad32-11e8-80c6-602120c8bb53.png)

![doomlauncher_2018-08-31_15-20-28](https://user-images.githubusercontent.com/25468624/44938180-22494f80-ad32-11e8-98e7-aca92ec1aec0.png)

![doomlauncher_2018-08-31_15-21-39](https://user-images.githubusercontent.com/25468624/44938181-24131300-ad32-11e8-8cbc-0ec51ae495df.png)

**Comment by hobomaster22** [comment]
This is a bug in 2.6.2. This bug is mostly fixed in the working 2.6.3 development build. If the file from the source port is removed and saved, then the form is reopened it will put the file back, which should also be fixed.

**Comment by robbinsrush** [comment]
Awesome. I was just looking for the source today to see if I could take a look at it. Good timing that you made your account just less than a week ago. 

Can't wait for 2.6.3! You have the best launcher hands down.

**Comment by hobomaster22** [comment]
Merged into master and fixed with pull request:

[https://github.com/hobomaster22/DoomLauncher/pull/30](url)
