### ISSUE TITLE
Sync Status not detecting files properly

### ISSUE THREAD

**Issue by guynamederick** [hobomaster22/DoomLauncher#37]
When going into the sync status tab, every file is detected to be both not in the database and not found on the GameFiles directory. IWADs are also affected by this. This was found in the Release Candidate build.
![sync](https://user-images.githubusercontent.com/35357202/45270793-d8b1e080-b466-11e8-8793-0635968d661b.png)

**Comment by hobomaster22** [comment]
Fixed with: https://github.com/hobomaster22/DoomLauncher/tree/bug/sync_status
