### ISSUE TITLE
Source port view form "Play" button breaks additional files

### ISSUE THREAD

**Issue by guynamederick** [hobomaster22/DoomLauncher#39]
Could have sworn the null check fixed this...anyways the play button for the source port view form is known to be broke for a while, albeit if trying to play a source port without additional files no harm will occur. However, if one were to press the "play" button with a source port that has an additional file to it, all files aside of the selected IWAD will never launch. Basically, not only the additional file to the source port won't work, but every other local PWAD, PK3, DEH, etc. won't work even if you remove the source port additional file and try launching on a selected file(s).

![spbroke](https://user-images.githubusercontent.com/35357202/45324262-3c91e300-b513-11e8-87d2-e341c145a59d.png)
![d2fail](https://user-images.githubusercontent.com/35357202/45324269-4287c400-b513-11e8-870e-9247306a8182.png)
Below I tried to launch Icarus: Alien Vanguard (it's not an additional file for the source port), only to just get the Doom 2 title screen. I tried removing the additional file from the source port edit form but no different.
![icfail](https://user-images.githubusercontent.com/35357202/45324448-c346c000-b513-11e8-970f-9d715ace76b4.png)

Currently the workaround to this is deleting the affected source port and readding it.

**Comment by robbinsrush** [comment]
My "Play" button doesn't even work half the time. It worked for a while and now it doesn't load any menu at all.

**Comment by guynamederick** [comment]
The current development build (from the dev branch) removed the "Play" button from the source port view form, and honestly there's already multiple ways to launch files that it doesn't seem needed anymore. However, source port additional files are currently broken in the branch (basically just adding a file is enough to break), so that says a lot of how broken that "Play" button has been.

**Comment by hobomaster22** [comment]
Are you saying the source port additional files is still an issue even with the play button removed? I haven't seen an issue with it.

**Comment by hobomaster22** [comment]
This is probably happening because clicking Save is removing -file parameter option.

**Comment by hobomaster22** [comment]
This is fixed and merged into 2.6.3.0_bugfixes and development.
