### ISSUE TITLE
Deleting a utility gives Source Port delete warning and shows Source Port list.

### ISSUE THREAD

**Issue by robbinsrush** [hobomaster22/DoomLauncher#42]
![image](https://user-images.githubusercontent.com/25468624/45385806-9e5f5500-b5c6-11e8-9224-4faee5051b53.png)

After clicking "Ok"

![image](https://user-images.githubusercontent.com/25468624/45385775-8f78a280-b5c6-11e8-96c1-2706d67f97c5.png)

**Comment by hobomaster22** [comment]
Fixed with https://github.com/hobomaster22/DoomLauncher/tree/bug/utility_delete
