### ISSUE TITLE
Suggestion: Use AppVeyor for CI

### ISSUE THREAD

**Issue by robbinsrush** [hobomaster22/DoomLauncher#45]
**!NOTE! to future people looking in: The AppVeyor links may be outdated due to me redoing the project to test things.**

I tested a fork of this project on my profile and without dealing with any .yml stuff, was able to build the project and run all Unit Tests. Sadly, to get past the current failing errors I had to disable testing, but we're still able to get automatically generated release .zips of the project with all tests ran with every commit.

If you want to take a peak on how it looks on my setup:

With the failed build:

https://ci.appveyor.com/project/robbinsrush/doomlauncher/build/1.0.1

With the tests disabled and set to upload the release .zip as an artifact to the site:

https://ci.appveyor.com/project/robbinsrush/doomlauncher/build/1.0.3

Edit: Or you can just release it straight to GitHub releases

![image](https://user-images.githubusercontent.com/25468624/45403115-b0181b00-b60d-11e8-8c8a-f9c6c386b21e.png)

**Comment by hobomaster22** [comment]
This looks cool, thanks for posting. I wonder why those unit tests are failing on their server. They both have to deal with files but they are not the only tests that deal with creating/modifying files. Could be the classic "works on my machine" problem...

Will have to look into this.

**Comment by guynamederick** [comment]
Interesting how it's only the CNDoom test that is failing, and I seem to get the same error on the UnitTest myself as well. On the bright side, all the other tests are working good, so no vital features or anything are buggy to say the least.

**Comment by robbinsrush** [comment]
I was trying to see if I could fix those failing tests (because both of those failed on my machine before I even touched that CI) last night and it got ugly. I think there may be an issue with the Cndoomstats reader, or maybe something about the test method. I'm leaning towards the reader itself

And the file modified also failed on my machine, but sometimes worked and didn't. I gave up.

**Comment by robbinsrush** [comment]
Aw geez. Maybe make sure there's no diffs inbetween the github version and your local version on both the test and the StatReader? Maybe even DoomLauncher.DataSources. This is weird, to say the least.

Doing a fresh download shows only CnDoom being the bad one.

![image](https://user-images.githubusercontent.com/25468624/45458193-56642f00-b6a7-11e8-833e-f569dfd7aac6.png)

**Comment by robbinsrush** [comment]
@guynamederick Humor me, see if doing a fresh download of the repo and going straight to Run All Tests causes any tests to fail.

And we can set scripts to run on the CI to make sure that certain files are placed in specific places or whatever is needed to make these tests pass.

**Comment by guynamederick** [comment]
@robbinsrush Yet again the test file for CNDoom failed on me, not sure what you were expecting. I also tried repairing Visual Studio 2017 and whatever I thought I was missing but no luck. And by what you're saying, skipping the CNDoom stats file would sound like the best option at the moment, the error is really odd to figure out here.

**Comment by guynamederick** [comment]
@robbinsrush Update, got it working! Try out this file, and if it works for you, I'll do a commit.
[test_cndoom.zip](https://github.com/hobomaster22/DoomLauncher/files/2377391/test_cndoom.zip)

**Comment by robbinsrush** [comment]
![image](https://user-images.githubusercontent.com/25468624/45461882-312cec00-b6ba-11e8-990d-c92359fa80a1.png)

Hot diggity damn, what do you know.

And the File Modified one passed, too. I'll send this over to the CI and see how it reacts.

**Comment by guynamederick** [comment]
And all I did was used a new stdout.txt file and pasted it there...coding is fun. :)

Alright, I'll be doing a commit on the development branch. Glad to hear it worked!

**Comment by robbinsrush** [comment]
And the CI still is unhappy.

*groan*

![image](https://user-images.githubusercontent.com/25468624/45462128-5ec66500-b6bb-11e8-8da0-48bc969a1f19.png)


https://github.com/robbinsrush/DoomLauncher/commit/8f2c5f5efda7d3a7a0254178d54706547ef5d732 The commit it tried to build.

**Comment by guynamederick** [comment]
Arrrghh, and I thought this would get by. This "bug" is really just not worth working over, seems like TestCnDoomStats should be excluded from testing for CI, nothing is making sense here.

**Comment by robbinsrush** [comment]
I'll send in a pull with those ignored. RIP in pep.

@hobomaster22 Let us know if this goes against your moral code to skip Unit Tests 😄 

If you need help setting up the CI, I'll gladly help.

**Comment by hobomaster22** [comment]
@robbinsrush It does go against my moral code, but in this case I think it's best to skip them for now. I will create another issue on these unit tests specifically.

**Comment by hobomaster22** [comment]
I installed VS on my desktop and luckily both these unit tests failed. They should be fixed on this branch. If you guys could confirm they work for you too that would be great!

https://github.com/hobomaster22/DoomLauncher/tree/bug/unit_test

**Comment by guynamederick** [comment]
It passed. What you did there to make it work is just amazing, that CnDoomStatsTest can't annoy anybody now. Looks like the unit tests should be good to go.
![pass](https://user-images.githubusercontent.com/35357202/45588650-85fc7c80-b8dd-11e8-8971-a96b1d9f0ffe.png)

**Comment by guynamederick** [comment]
@robbinsrush With this out of the way, you won't mind setting up the AppVeyor CI yourself and doing a pull request for that? Seems to me you're getting that set up. :)
