### ISSUE TITLE
Feature Request: Automatically generate required folders and SQLite file when missing

### ISSUE THREAD

**Issue by robbinsrush** [hobomaster22/DoomLauncher#52]
Right now if a folder/the SQLite file is missing the program refuses to start, but it could make stuff easier on an end user if empty folders and databases are generated.

I see this happens when debugging, so is there a reason that this isn't enabled on a Release build?

https://github.com/hobomaster22/DoomLauncher/blob/6acf264a8524c197b2dc83c0482c57ea05647522/DoomLauncher/Forms/MainForm_Init.cs#L72

**Comment by guynamederick** [comment]
There is already the backup folder for Doom Launcher, so maybe moving the most recent backup available to the DoomLauncher directory when opening the launcher might be appropriate here.

**Comment by hobomaster22** [comment]
This functionality was added for running Doom Launcher in debug from visual studio. When running in debug it generates the files and the DoomLauncher.sqlite in the project is set to copy to the directory. Having this function would give you the ability to run it in release from visual studio.

The release package zip is supposed to have everything to run the application for end users.

**Comment by robbinsrush** [comment]
Yeah but you have to consider those who don't always follow instructions/copy the wrong things/want a simple copy.

Up to you in the end. :)
