### ISSUE TITLE
2.6.3.0 selecting multiple mods doesn't work

### ISSUE THREAD

**Issue by ak1dd** [hobomaster22/DoomLauncher#73]
select a local mod, select Play,  In the additional Files/Load order list select the Add button.  Choose multiple additional files.  Select OK.  Now look at Show Launch Parameters - only the FIRST additional file chosen is added.  IF I only choose one at a time it works correctly.

UPDATE: ok I figured out how to make this work.  If you choose "Select Individual Files" I can select individually.   My question is why do I have to do that?  I get there may be more than one file in an archive -but if I explicitly select an archive - like lights.pk3 (or lights.zip), why do I also have to go in and select an individual file sometimes?   Is DL trying to be smart about mod conflicts?

**Comment by hobomaster22** [comment]
Can you attach your DoomLauncher.sqlite file and let me know exactly what files you are selecting? This way I can see the exact issue, thanks!

**Comment by ak1dd** [comment]
I can do it with most combinations when I add more than one mod - there are no duplicates in zips.  Look at the attached screenshot.  I added "Additional Files",  selected Brutal Doom, BetterSelectingAnimations and EnhancedBulletPuffs - only BetterSelectingAnimations is selected if I choose "Select Individual Files".  Only that specific pk3 is loaded if I hit OK to play.

I can do this if I select a few mods for almost any combination.


[DoomLauncher.zip](https://github.com/hobomaster22/DoomLauncher/files/2746071/DoomLauncher.zip)



![2019-01-10 07_49_56-doom launcher](https://user-images.githubusercontent.com/38289720/50979942-6e5c8b80-14ac-11e9-9cc9-7b45d6d8cef6.png)

**Comment by hobomaster22** [comment]
Thanks, I have figured out the problem. You can verify it's fixed by downloading the latest development build:
https://ci.appveyor.com/api/buildjobs/smnalbga63k3jt95/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.0.zip

**Comment by ak1dd** [comment]
FIXED!!!!   Now please fix the longstanding ID/GZDoom issue of not having per-game/wad savegames only!!  :)   Seriously, thank you.

Not sure if I close or you do?
