### ISSUE TITLE
Allow updating a mod/map 

### ISSUE THREAD

**Issue by ak1dd** [hobomaster22/DoomLauncher#78]
I have edited the description/tags/etc for a wad.  An update comes along - I have to do it all again or cut/paste each field?  Is there a way to do this by just updating the ZIP an existing record uses?

**Comment by hobomaster22** [comment]
Fixed in latest dev build:
https://ci.appveyor.com/api/buildjobs/3h607tfolohj7i2c/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.0.zip
