### ISSUE TITLE
Sort on untagged

### ISSUE THREAD

**Issue by ak1dd** [hobomaster22/DoomLauncher#81]
is there any way to see files that are untagged?  Sometimes you forget and a large list means there is kruft I may never get to...  Maybe a fixed "untagged" tab (or an option to show an untagged tab)

**Comment by hobomaster22** [comment]
Added Untagged tab.

You can download the development version here:
https://ci.appveyor.com/api/buildjobs/49f0dh6sjkcvvexb/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip
