### ISSUE TITLE
clicking URL links in Comments doesn't work

### ISSUE THREAD

**Issue by ak1dd** [hobomaster22/DoomLauncher#83]
it is underlined and blue - expect it to open a browser in that link.   I use it to track mods that don't always have moddb or other common sites

**Comment by hobomaster22** [comment]
Fixed in latest dev build:
https://ci.appveyor.com/api/buildjobs/3h607tfolohj7i2c/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.0.zip
