### ISSUE TITLE
[Feature Request] Pull metadata from ModDB

### ISSUE THREAD

**Issue by PopeRigby** [hobomaster22/DoomLauncher#88]

**Comment by guynamederick** [comment]
There is no API available from ModDB and that seems highly unlikely anytime soon. And personally, ModDB is highly unreliable to find Doom mods unless it's the creator/uploader of a file or project is by someone talented.

Also, please request features that can be useful for Doom Launcher, not cumbersome or not possible.

**Comment by PopeRigby** [comment]
My apologies, I didn't know ModDB had no API.
