### ISSUE TITLE
File E:/Games/Doom Modding/DoomLauncher/GameFiles/Temp/gzdoom.pk3 is overriding core lump mapinfo/ultdoom.txt.

### ISSUE THREAD

**Issue by PopeRigby** [hobomaster22/DoomLauncher#89]

**Comment by guynamederick** [comment]
What are you trying to do here? gzdoom.pk3 should never be in the Temp directory, GZDoom will automatically load it in if launching the .exe. You don't need to do anything with the source port directory files like doomretro.wad, gzdoom.pk3, etc.

**Comment by PopeRigby** [comment]
I didn't put it in there. Should I just delete it?

**Comment by guynamederick** [comment]
What mod were you trying to load? If what you have downloaded includes the GZDoom source port (like Doom Slayer Chronicles), just delete everything that aren't the main mod files.

**Comment by PopeRigby** [comment]
That fixed it.
