### ISSUE TITLE
Selecting individual files doesn't work

### ISSUE THREAD

**Issue by PopeRigby** [hobomaster22/DoomLauncher#90]
Clicking on 'Select Individual Files', selecting your files and then clicking 'OK' from the launch menu causes no files to be loaded.  Vanilla Doom is loaded instead.

**Comment by hobomaster22** [comment]
Can you attach your DoomLauncher.sqlite file and let me know what you were loading?

**Comment by PopeRigby** [comment]
[DoomLauncher.sqlite](https://drive.google.com/file/d/1qi877mtImTKwLesa_zb_ass5DnP_GOM_/view?usp=sharing)

Things being loaded
- Guncaster
- Bolognese Gore Mod
- Rock's Crosshair Pack

**Comment by PopeRigby** [comment]
It happens with all other mods as well

**Comment by hobomaster22** [comment]
Strange, I'm not seeing an issue. Can you give a very specific scenario like the exact mod you loaded with what and the individual files you selected? I used your database and loaded crosshairs with doom2 without an issue.
![file1](https://user-images.githubusercontent.com/42744211/52912827-f93b5d80-3284-11e9-93fb-09407249b17f.png)
![file2](https://user-images.githubusercontent.com/42744211/52912828-f93b5d80-3284-11e9-9b14-088ae634c84c.png)

You can also click the 'Preview Parameters' button to see how Doom Launcher builds the launch parameters and what files are being sent to the source port.

**Comment by PopeRigby** [comment]
Maybe the problem is that is isn't saving my selections when I click OK after selecting the files. Here's a video: https://youtu.be/CfdUHWop7ek

**Comment by PopeRigby** [comment]
Here's some more strange behavior: https://youtu.be/Z2Oo__khpk4

**Comment by hobomaster22** [comment]
Thanks, the videos were very helpful. The first issue has been resolved in the development build for a while. I've been behind on releasing the newest version. It's caused by the sub folder in the archive.

You can download the development build here and it should resolve that issue:
https://ci.appveyor.com/project/hobomaster22/doomlauncher/build/artifacts

**Comment by PopeRigby** [comment]
How can I update without wiping everything?

**Comment by hobomaster22** [comment]
You just copy everything from the zip into your Doom Launcher folder. It won't overwrite your database or game files.

**Comment by PopeRigby** [comment]
That fixed it. Thank you!
