### ISSUE TITLE
Time played in HH:MM:SS + show last map played and number against total

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#91]
I suggest time played should bes shown as hours : minutes : seconds instead of "2,84 hours".

Also the number/name of the last map being played (and perhaps against total number of maps) could be shown to know progress.

**Comment by mgtroyas** [comment]
I realized there is a lot of detail about maps and runs on the Info tab. So second part of the request was already covered, my bad.

The main part of the request, I should clarify, is simply showing total gameplay in hours:min instead of a decimal of hours (1.03 hours).

**Comment by hobomaster22** [comment]
I was thinking something like this:

![summary](https://user-images.githubusercontent.com/42744211/56471128-c9dbd500-641c-11e9-976c-faabe2f3120a.png)

**Comment by hobomaster22** [comment]
Done. You can check it out here:

https://ci.appveyor.com/api/buildjobs/bmu5naucaktg932t/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Tested and working properly. Looks pretty good!

**Comment by mgtroyas** [comment]
Just noticed this build has the text descripton field non operational.

**Comment by hobomaster22** [comment]
What text field do you mean?

**Comment by mgtroyas** [comment]
The big one with the description of the file, placed just below your screenshot, on the side bar.

**Comment by hobomaster22** [comment]
Nice catch! Should be fixed here:
https://ci.appveyor.com/api/buildjobs/xghnpbabiv2ywswk/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Yes, it's working now!
