### ISSUE TITLE
Untagged tab

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#94]
A tag for untagged elements.

**Comment by hobomaster22** [comment]
Added Untagged tab.

You can download the development version here:
https://ci.appveyor.com/api/buildjobs/49f0dh6sjkcvvexb/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Works perfectly. Thank you very much.
