### ISSUE TITLE
Screenshot actions and browsing

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#97]
Screenshots management is a great feature but some enhancements could make it more useful:
- Double-click on a screenshot should launch the viewer as "Open File..." option on context menu already does.
- Sending not only the currently selected but all the images related to the file to the image viewer, so you can natively browse left and right between them.
- Option to choose screenshots thumbnail size?
- Perhaps on the right bar screenshot inside the main window, add small buttons to browse between screenshots.
- Buttons to maximize/restore the screenshots pane over the application window, to see more of them. Or open it on a secondary window, with selected one in full size and butons to browse left and right.

**Comment by hobomaster22** [comment]
Hi, I think this build should have everything you're looking for. Choosing the thumbnail size is in: Main Menu -> Settings. You can double click the screenshot and get a custom screenshot viewer. You will have to click the image first, and then double click due to a quirk in windows.

https://ci.appveyor.com/api/buildjobs/dw9vkth0qam1cp5x/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Once again it's looking great!

A couple of suggestions:

In the full viewer I'd make possible browsing between screenshots by mouse wheel, and use keyboard keys:
- arrow keys toprev next image
- home/end keys for first/last image
- delete key to delete current image, perhaps a dedicated button near save image on the bottom toolbar.

Also if I press restore button from maximized default state, the window is resized to an intermediate size and centered but then instantly moved to the top left screen corner. I think it should stay centered.

On the screenshots pane, in order to hint the user about double clicking I'd add a tooltip when hovering the mouse over it saying "Double click to view full size".

**Comment by hobomaster22** [comment]
I added the mouse wheel and keyboard keys. There is now a tooltip for the screenshots too.

As for restoring the viewer, it appears to be a winforms issue that it ignores the CenterParent flag when the dialog is set to maximized.

The delete is not trivial and actually requires changing a significant amount of code through the launcher so I will be holding off on that for now.

https://ci.appveyor.com/api/buildjobs/euet2laf0mrgb07s/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Noticed the mousewheel down goes to previous image, mousewheel up to next. Perhaps the other way arround would be the expected behaviour?

**Comment by hobomaster22** [comment]
Oops, you are right it is backwards. Should be fixed here:
https://ci.appveyor.com/api/buildjobs/1r450yghnp2yinp9/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Everything fine now. Thank you very much!
