### ISSUE TITLE
Minor layout suggestions

### ISSUE THREAD

**Issue by mgtroyas** [hobomaster22/DoomLauncher#99]
Just a couple of suggestion.

Perhaps sidebar is getting too cramped and could leave too little space for description text on lower resolutions / smaller window sizes. I'd try reducing vertical padding inside the "time played", "last map" and "tags" sections to match the "maps/kills/secrets/items" one.

Also perhaps automap icon is taking too much space and gets too near the horizontal divisor. The icons could be downsized to a common height, to gain some space and homogeneity.

**Comment by hobomaster22** [comment]
I made some tweaks to the layout. Let me know what you think:
https://ci.appveyor.com/api/buildjobs/ddmu62w199v3x9wi/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Hey, looks much better now!

Just a suggestion, progress bars (count of maps, items, etc) have fixed width so if sidebar is too narrow they are partially hidden, if too wide lot of free space is left on the side. Could be possible to define a dynamic size, just to always leave a fixed free margin to the right? (like screenshot does)

**Comment by hobomaster22** [comment]
Progress bars should resize now:
Should be resolved with this build:
https://ci.appveyor.com/api/buildjobs/a90s6kar95p1kyl2/artifacts/ReleaseBuild%2FDoomLauncher_2.6.4.1.zip

**Comment by mgtroyas** [comment]
Yes, it's also working here, thank you very much.
